project:
  type: website
  output-dir: docs

website:
  title: "Chan Min Min"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



